### ISSUE TITLE
[RSS] ArgumentNullException on valid endpoint

### ISSUE THREAD

**Issue by acesyde** [higty/higlabo#11]
Hi,

I have test with a valide rss enpoint but in the RSS library an error throw

Endpoint RSS :
http://www.cannes.maville.com/flux/rss/actu.php

Error :
System.ArgumentNullException: Value cannot be null.
Parameter name: ns
   at System.Xml.Linq.XNamespace.op_Addition(XNamespace ns, String localName)
   at HigLabo.Rss.RssItem_2_0.Parse(XElement element)
   at HigLabo.Rss.Rss_2_0_Parser.CreateRssItem(XElement element)
   at HigLabo.Rss.RssParser.<Parse>b__3_0(XElement el)

Can you check please ?

Thks a lot

**Comment by higty** [comment]
Hi.

I checked your endpoint.
It seems like this endpoint return 403 and invalid rss format.
Please check your endpoint.

regards.

**Comment by acesyde** [comment]
Hmm it's work for me maybe IP restriction  ?

This is the content :)

```xml
<?xml version="1.0" encoding="utf-8"?>
<rss version="2.0">
<channel>
<title>Cannes : actu quotidienne </title>
<link>http://www.cannes.maville.com</link>
<description>Articles de la presse quotidienne sur Cannes</description>
<language>fr</language> 
<image>
<url>http://www.cannes.maville.com/design/images/LogoMaville.gif</url> 
<title>Cannes : actu quotidienne</title> 
<link>http://www.cannes.maville.com</link> 
<width>80</width> 
<height>27</height> 
</image>
<item>
<title><![CDATA[Un chien nageant dans une piscine filmé sous l'eau [VIDEO] (Ouest-France)]]></title>
<link><![CDATA[http://www.cannes.maville.com/actu/actudet_-un-chien-nageant-dans-une-piscine-filme-sous-l-eau-[video]_fil-3207505_actu.Htm?xtor=RSS-4&utm_source=RSS_MVI_cannes&utm_medium=RSS&utm_campaign=RSS]]></link>
<description><![CDATA[Lundi 22 mai 2017<br />Il y a zéro info dans cette vidéo. Mais il y a Zéro. Un adorable corgi (vous savez une race de chiens originaires du Pays de Galles) qui nage dans une piscine à Simi Valley, en Californie.<br /><br />]]></description>
<enclosure url="http://www.cannes.maville.com/photosmvi/2017/05/22/P1D3207505G_px_100_.jpg" type="image/jpeg"></enclosure>

</item>
<item>
<title><![CDATA[Ce chat dort sur le dos, les quatre pattes en l’air [VIDEO] (Ouest-France)]]></title>
<link><![CDATA[http://www.cannes.maville.com/actu/actudet_-ce-chat-dort-sur-le-dos-les-quatre-pattes-en-l-air-[video]_fil-3207502_actu.Htm?xtor=RSS-4&utm_source=RSS_MVI_cannes&utm_medium=RSS&utm_campaign=RSS]]></link>
<description><![CDATA[Lundi 22 mai 2017<br />Habituellement un chat est toujours sur le qui-vive même lorsqu’il est endormi. Un chat complètement détendu c’est rare mais on en a trouvé un !<br /><br />]]></description>
<enclosure url="http://www.cannes.maville.com/photosmvi/2017/05/22/P1D3207502G_px_100_.jpg" type="image/jpeg"></enclosure>

</item>
<item>
<title><![CDATA[Le bijou fantaisie était en fait un diamant de 26 carats (Ouest-France)]]></title>
<link><![CDATA[http://www.cannes.maville.com/actu/actudet_-le-bijou-fantaisie-etait-en-fait-un-diamant-de-26-carats_fil-3207510_actu.Htm?xtor=RSS-4&utm_source=RSS_MVI_cannes&utm_medium=RSS&utm_campaign=RSS]]></link>
<description><![CDATA[Lundi 22 mai 2017<br />Acheté dans une brocante comme un bijou fantaisie pour une somme insignifiante, un solitaire en diamant de 26 carats va être vendu aux enchères chez Sotheby’s à Londres pour un prix estimé entre 250 000 et 350 000 livres (jusqu’à 450 000 €).<br /><br />]]></description>
<enclosure url="http://www.cannes.maville.com/photosmvi/2017/05/22/P1D3207510G_px_100_.jpg" type="image/jpeg"></enclosure>

</item>


</channel>
</rss> 
```

**Comment by higty** [comment]
Hi.

I merged your pull request.
Thank you for your contribution!
